### ISSUE TITLE
Review Licensing changes due to the addition of Swift-Crypto

### ISSUE THREAD

**Issue by pacu** [zcash-hackworks/MnemonicSwift#12]
Reference: 
@daira pointed out this conflict https://github.com/zcash-hackworks/MnemonicSwift/pull/10#issuecomment-995166413

we need specific review to know if this was addressed or if we need further adjustments

**Comment by str4d** [comment]
I also note that the `README` says that the license is MIT, but the repository has both `LICENSE-APACHE` and `LICENSE-MIT`. If the intent is to dual-license `MIT OR Apache-2.0` then I suggest adopting the wording from typical Rust projects, including the `Contribution` sub-section. See e.g. https://github.com/zcash/librustzcash/blob/master/zcash_primitives/README.md

**Comment by daira** [comment]
https://github.com/zcash-hackworks/MnemonicSwift#license should say:
```
## License

Copyright 2017-2021 CikeQiu.
Copyright 2020-2021 The Electric Coin Company.

Licensed under either of

 * Apache License, Version 2.0, ([LICENSE-APACHE](LICENSE-APACHE) or
   http://www.apache.org/licenses/LICENSE-2.0)
 * MIT license ([LICENSE-MIT](LICENSE-MIT) or http://opensource.org/licenses/MIT)

at your option.

### Contribution

Unless you explicitly state otherwise, any contribution intentionally
submitted for inclusion in the work by you, as defined in the Apache-2.0
license, shall be dual licensed as above, without any additional terms or
conditions.
```
(The copyright for CikeQiu should not have been removed in 2657bdadf7bd6594293730a8ba25735865a8ce0f.)
